import { AlertTriangle, Archive, ChevronRight, FolderOpen, RotateCcw } from 'lucide-react';
import type { Category, HistoryEntry } from '../types';
import { Modal } from './Modal';

const formatDate = (timestamp: number | null) => timestamp ? new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(timestamp) : '从未打开';

export function HistoryDialog({ history, categories, onUndo, onReveal, onClose }: { history: HistoryEntry[]; categories: Category[]; onUndo: (id: string) => Promise<void>; onReveal: (id: string) => Promise<void>; onClose: () => void }) {
  return <Modal title="整理记录" onClose={onClose} wide><div className="history-list">{history.map((entry) => <section className="history-record" data-history-id={entry.id} key={entry.id}><div className="history-entry"><div className="history-icon"><Archive size={18} /></div><span><strong>{entry.categoryLabel || categories.find((category) => category.id === entry.categoryId)?.label || '桌面归档'}</strong><small>{formatDate(entry.timestamp)} · {entry.itemCount || entry.operations.length} 个项目</small></span><em className={entry.undone ? 'undone' : ''}>{entry.undone ? '已撤销' : entry.status === 'partial' || entry.status === 'partially-undone' ? '部分完成' : entry.status === 'failed' ? '失败' : '可撤销'}</em><button className="icon-button" title={entry.type === 'shortcut-repair' ? '定位快捷方式' : '打开归档位置'} onClick={() => onReveal(entry.id)}><FolderOpen size={15} /></button><button className="icon-button" title={entry.lastUndoFailures?.length ? '重试撤销失败项目' : entry.type === 'shortcut-repair' ? '撤销快捷方式修复' : '撤销本次整理'} disabled={entry.undone || !(entry.pendingOperations?.length ?? entry.operations.length)} onClick={() => onUndo(entry.id)}><RotateCcw size={15} /></button></div><details className="history-details"><summary>查看路径与结果</summary>{entry.operations.map((operation) => <div className="history-path" key={`${entry.id}-${operation.id}`}><span>{operation.source}</span><ChevronRight size={14} /><span>{operation.target}</span></div>)}{entry.failedOperations?.map((operation) => <div className="history-path failed" key={`${entry.id}-failed-${operation.id}`}><AlertTriangle size={14} /><span>{operation.name || operation.id}：{operation.reason}</span></div>)}</details></section>)}{history.length === 0 && <div className="data-empty">还没有整理或修复记录</div>}</div></Modal>;
}
