import { useRef, useState } from 'react';
import type { AppSettings } from '../types';
import { Modal } from './Modal';

export function SettingsDialog({ settings, onClose, onSave }: { settings: AppSettings; onClose: () => void; onSave: (patch: Partial<AppSettings>) => Promise<void> }) {
  const [draft, setDraft] = useState(settings);
  const initialSettings = useRef(settings);
  const [busy, setBusy] = useState(false);
  const hotkeyOptions = ['Ctrl+Alt+D', 'Ctrl+Shift+Space', 'Alt+Shift+D'];
  const autoHideControlsDisabled = draft.quickPanelPinned || !draft.quickPanelAutoHide;
  return <Modal title="设置" onClose={onClose}><div className="settings-form">
    <label><span><strong>界面主题</strong><small>可跟随 Windows 主题切换</small></span><select value={draft.theme} onChange={(event) => setDraft({ ...draft, theme: event.target.value as AppSettings['theme'] })}><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></label>
    <label><span><strong>卡片密度</strong><small>调整网格中每屏显示的项目数量</small></span><select value={draft.gridDensity} onChange={(event) => setDraft({ ...draft, gridDensity: event.target.value as AppSettings['gridDensity'] })}><option value="compact">紧凑</option><option value="comfortable">标准</option><option value="large">宽松</option></select></label>
    <label><span><strong>桌面工作台图标大小</strong><small>图标、名称文字和项目高度同步缩放</small></span><span className="settings-range"><input aria-label="桌面工作台图标大小" type="range" min="80" max="160" step="5" value={draft.workspaceItemScale} onChange={(event) => setDraft({ ...draft, workspaceItemScale: Number(event.target.value) })} /><output>{draft.workspaceItemScale}%</output></span></label>
    <label><span><strong>快速面板图标大小</strong><small>同时作用于列表、图标排列和搜索结果</small></span><span className="settings-range"><input aria-label="快速面板图标大小" type="range" min="80" max="160" step="5" value={draft.quickPanelItemScale} onChange={(event) => setDraft({ ...draft, quickPanelItemScale: Number(event.target.value) })} /><output>{draft.quickPanelItemScale}%</output></span></label>
    <label><span><strong>隐藏空分类</strong><small>侧栏不显示当前没有项目的工作场景</small></span><input type="checkbox" checked={draft.hideEmptyCategories} onChange={(event) => setDraft({ ...draft, hideEmptyCategories: event.target.checked })} /></label>
    <label><span><strong>开机启动</strong><small>启动后驻留系统托盘</small></span><input type="checkbox" checked={draft.launchAtStartup} onChange={(event) => setDraft({ ...draft, launchAtStartup: event.target.checked })} /></label>
    <label><span><strong>开机静默驻留</strong><small>开机启动时不自动弹出主窗口</small></span><input type="checkbox" checked={draft.launchAtStartupHidden} onChange={(event) => setDraft({ ...draft, launchAtStartupHidden: event.target.checked })} /></label>
    <label><span><strong>关闭到托盘</strong><small>关闭主窗口后仍可使用快速面板</small></span><input type="checkbox" checked={draft.closeToTray} onChange={(event) => setDraft({ ...draft, closeToTray: event.target.checked })} /></label>
    <label><span><strong>固定快速面板</strong><small>始终展开显示，优先于自动隐藏设置</small></span><input type="checkbox" checked={draft.quickPanelPinned} onChange={(event) => setDraft({ ...draft, quickPanelPinned: event.target.checked })} /></label>
    <label><span><strong>边缘自动隐藏</strong><small>鼠标移开后收起，只保留屏幕边缘触发带</small></span><input type="checkbox" checked={draft.quickPanelAutoHide} onChange={(event) => setDraft({ ...draft, quickPanelAutoHide: event.target.checked })} /></label>
    <div className="settings-row"><span><strong>停靠位置</strong><small>也可拖动面板到任一有效外部边缘</small></span><div className="settings-segmented" role="group" aria-label="快速面板停靠位置">{([['top', '顶部'], ['left', '左侧'], ['right', '右侧']] as const).map(([value, label]) => <button type="button" key={value} className={draft.quickPanelDockPosition === value ? 'active' : ''} aria-pressed={draft.quickPanelDockPosition === value} onClick={() => setDraft({ ...draft, quickPanelDockPosition: value })}>{label}</button>)}</div></div>
    <label><span><strong>边缘吸附距离</strong><small>接近有效外边缘 {draft.quickPanelSnapDistance} 像素时显示停靠预览</small></span><span className="settings-range"><input aria-label="边缘吸附距离" type="range" min="8" max="80" step="2" value={draft.quickPanelSnapDistance} onChange={(event) => setDraft({ ...draft, quickPanelSnapDistance: Number(event.target.value) })} /><output>{draft.quickPanelSnapDistance} px</output></span></label>
    <label className={autoHideControlsDisabled ? 'disabled-row' : ''}><span><strong>自动隐藏延时</strong><small>鼠标移开 {draft.quickPanelHideDelay / 1000} 秒后收起</small></span><span className="settings-range"><input aria-label="自动隐藏延时" type="range" min="300" max="3000" step="100" disabled={autoHideControlsDisabled} value={draft.quickPanelHideDelay} onChange={(event) => setDraft({ ...draft, quickPanelHideDelay: Number(event.target.value) })} /><output>{draft.quickPanelHideDelay / 1000} 秒</output></span></label>
    <label className={autoHideControlsDisabled ? 'disabled-row' : ''}><span><strong>边缘触发区域</strong><small>区域越宽越容易唤出，建议 8 像素</small></span><span className="settings-range"><input aria-label="边缘触发区域" type="range" min="3" max="24" step="1" disabled={autoHideControlsDisabled} value={draft.quickPanelTriggerSize} onChange={(event) => setDraft({ ...draft, quickPanelTriggerSize: Number(event.target.value) })} /><output>{draft.quickPanelTriggerSize} px</output></span></label>
    <label className={draft.reduceMotion ? 'disabled-row' : ''}><span><strong>滑出速度</strong><small>数值越小，面板展开与收起越快</small></span><span className="settings-range"><input aria-label="快速面板滑出速度" type="range" min="80" max="500" step="20" disabled={draft.reduceMotion} value={draft.quickPanelSlideDuration} onChange={(event) => setDraft({ ...draft, quickPanelSlideDuration: Number(event.target.value) })} /><output>{draft.quickPanelSlideDuration} ms</output></span></label>
    <label><span><strong>减少动态效果</strong><small>关闭非必要的界面过渡</small></span><input type="checkbox" checked={draft.reduceMotion} onChange={(event) => setDraft({ ...draft, reduceMotion: event.target.checked })} /></label>
    <label><span><strong>快速面板热键</strong><small>选择不与常用软件冲突的组合</small></span><select value={draft.hotkey} onChange={(event) => setDraft({ ...draft, hotkey: event.target.value })}>{!hotkeyOptions.includes(draft.hotkey) && <option value={draft.hotkey}>{draft.hotkey}</option>}{hotkeyOptions.map((hotkey) => <option value={hotkey} key={hotkey}>{hotkey}</option>)}</select></label>
  </div><footer className="modal-footer"><button className="secondary-button" disabled={busy} onClick={onClose}>取消</button><button className="primary-button" disabled={busy} onClick={async () => { setBusy(true); try { const patch = Object.fromEntries(Object.entries(draft).filter(([key, value]) => JSON.stringify(value) !== JSON.stringify(initialSettings.current[key as keyof AppSettings]))) as Partial<AppSettings>; await onSave(patch); onClose(); } finally { setBusy(false); } }}>保存设置</button></footer></Modal>;
}
